[package]
name = "orphos-cli"
version = "0.3.0"
edition = "2024"
rust-version = "1.89"
description = "Command-line interface for Orphos, a tool for finding protein-coding genes in microbial genomes."
license = "GPL-3.0-or-later"
repository = "https://github.com/FullHuman/orphos"
documentation = "https://docs.rs/orphos-cli"
readme = "README.md"
categories = ["science::bioinformatics", "command-line-utilities"]
keywords = [
    "orphos",
    "bioinformatics",
    "genomics",
    "prodigal"
]
exclude = ["tests/data/**"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
orphos-core = { version = "0.3.0", path = "../orphos-core" }

[dev-dependencies]
tempfile = "3.27.0"
assert_cmd = "2.2.2"
predicates = "3.1.4"
similar = "3.1.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
criterion = { version = "0.8.2", features = ["html_reports"] }
insta = { version = "1.48.0", features = ["glob"] }
sha2 = "0.11.0"

[[bin]]
name = "orphos"
path = "src/main.rs"

[[bench]]
name = "prodigal_benchmarks"
harness = false

[[bench]]
name = "ecoli_single_threaded_orphos"
harness = false
